apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
  namespace: hello-flask
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      default:
        cpu: 250m
        memory: 256Mi
