apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hello-flask
  namespace: hello-flask
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-flask
      app.kubernetes.io/component: web
