apiVersion: v1
kind: ResourceQuota
metadata:
  name: hello-flask-quota
  namespace: hello-flask
spec:
  hard:
    pods: "20"
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "10"
    limits.memory: 10Gi
