{{- if .Values.gatewayApi.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "hello-flask.fullname" . }}
  labels:
    {{- include "hello-flask.labels" . | nindent 4 }}
spec:
  hostnames:
    {{- range .Values.ingress.hosts }}
    - {{ .host | quote }}
    {{- end }}
  parentRefs:
    - name: {{ .Values.gatewayApi.gatewayRef.name }}
      namespace: {{ .Values.gatewayApi.gatewayRef.namespace }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "hello-flask.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
