{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hello-flask.fullname" . }}-ingress
  labels:
    {{- include "hello-flask.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "hello-flask.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- range .Values.networkPolicy.allowIngressFrom }}
        - namespaceSelector:
            {{- toYaml .namespaceSelector | nindent 12 }}
          podSelector:
            {{- toYaml .podSelector | nindent 12 }}
        {{- end }}
  egress:
    {{- if .Values.networkPolicy.allowEgressToDNS }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- end }}
    - {}
{{- end }}
