{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hello-flask.fullname" . }}
  labels:
    {{- include "hello-flask.labels" . | nindent 4 }}
automountServiceAccountToken: {{ ternary "true" "false" .Values.serviceAccount.automount | lower }}
{{- end }}
